services:
  server:
    container_name: fs-server
    build : ./server
    image : fileshare-server
    ports:
      - "80:80"
    env_file:
      - ./server/.env
    networks:
      - fileshare-network
    depends_on:
      - postgres
      - redis
  postgres:
    container_name: fs-database
    image : postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=fileshare
    networks:
      - fileshare-network
    volumes:
      - fileshare-db:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

  redis:
    container_name: fs-redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - fileshare-redis:/data
    networks:
      - fileshare-network

  
networks:
  fileshare-network:
    driver: bridge

volumes:
  fileshare-db:
  fileshare-redis: