services:
  server:
    container_name: fs-server
    build : ./server
    image : fileshare-server
    ports:
      - "80:80"
    env_file:
      - ./server/.env
    networks:
      - fileshare-network
    depends_on:
      - postgres
      - redis
      - mongodb
  postgres:
    container_name: fs-postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=fileshare
    volumes:
      - fileshare-postgres:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - fileshare-network

  redis:
    container_name: fs-redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - fileshare-redis:/data
    networks:
      - fileshare-network
  
  mongodb:
    container_name: fs-mongo
    image : mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - fileshare-network
    volumes:
      - fileshare-mongo:/data/db
  
networks:
  fileshare-network:
    driver: bridge

volumes:
  fileshare-postgres:
  fileshare-redis:
  fileshare-mongo: