services:
  client:
    container_name: fs-client
    build : ./client
    image : fileshare-client
    ports:
      - "5173:5173"
    env_file:
      - ./client/.env
    networks:
      - fileshare-network
    depends_on:
      - server
  
  server:
    container_name: fs-server
    build : ./server
    image : fileshare-server
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    networks:
      - fileshare-network
    depends_on:
      - postgres
    
  postgres:
    container_name: fs-database
    image : postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=fileshare
    networks:
      - fileshare-network
    volumes:
      - fileshare-db:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
  
networks:
  fileshare-network:
    driver: bridge

volumes:
  fileshare-db: